//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNuke.Tests.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetNuke.Tests.Data.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source={0};Integrated Security=True.
        /// </summary>
        internal static string AdminConnectionString {
            get {
                return ResourceManager.GetString("AdminConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source={0};Integrated Security=True;Initial Catalog={1}.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF (SELECT COUNT(*) FROM sys.databases WHERE [name] = &apos;{0}&apos;) &gt; 0
        ///  DROP DATABASE [{0}]
        ///CREATE DATABASE [{0}].
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM sys.databases WHERE [name] = &apos;{0}&apos;.
        /// </summary>
        internal static string DatabaseCountScript {
            get {
                return ResourceManager.GetString("DatabaseCountScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP DATABASE [{0}].
        /// </summary>
        internal static string DropDatabase {
            get {
                return ResourceManager.GetString("DropDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM {databaseOwner}{objectQualifier}{0}.
        /// </summary>
        internal static string EmptyTable {
            get {
                return ResourceManager.GetString("EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MAX({1}) FROM {databaseOwner}{objectQualifier}{0}.
        /// </summary>
        internal static string GetLastAddedRecordID {
            get {
                return ResourceManager.GetString("GetLastAddedRecordID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM {databaseOwner}{objectQualifier}{0} WHERE {1} = {2}.
        /// </summary>
        internal static string GetRecordsByField {
            get {
                return ResourceManager.GetString("GetRecordsByField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM sys.objects WHERE [name] = &apos;{objectQualifier}{0}&apos;.
        /// </summary>
        internal static string ObjectCountScript {
            get {
                return ResourceManager.GetString("ObjectCountScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlDataProvider.
        /// </summary>
        internal static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\Providers\DataProviders\SqlDataProvider\.
        /// </summary>
        internal static string ProviderPath {
            get {
                return ResourceManager.GetString("ProviderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotNetNuke.Data.SqlDataProvider.
        /// </summary>
        internal static string ProviderType {
            get {
                return ResourceManager.GetString("ProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM {databaseOwner}{objectQualifier}{0}.
        /// </summary>
        internal static string RecordCountScript {
            get {
                return ResourceManager.GetString("RecordCountScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBCC CHECKIDENT ({objectQualifier}{0}, RESEED, {1}).
        /// </summary>
        internal static string ReSeedIdentityColumn {
            get {
                return ResourceManager.GetString("ReSeedIdentityColumn", resourceCulture);
            }
        }
    }
}
