'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Html

    Partial Public Class EditHtml

        '''<summary>
        '''tblEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblEdit As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''txtContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContent As Global.DotNetNuke.UI.UserControls.TextEditor

        '''<summary>
        '''rowPublish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowPublish As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPublish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPublish As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkPublish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPublish As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cmdSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSave As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''cmdPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdPreview As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''dshReview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshReview As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblReview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblReview As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plComment As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtComment As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdReview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdReview As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''cmdCancel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel2 As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''dshVersions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshVersions As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblVersions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblVersions As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''grdVersions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdVersions As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''dshHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshHistory As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblHistory As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plVersion As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVersion As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plWorkflow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plWorkflow As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblWorkflow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkflow As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plState As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblState As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdLog control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdLog As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''dshPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshPreview As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblPreview As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPreview As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
