'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Html

    Partial Public Class Settings

        '''<summary>
        '''plReplaceTokens control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plReplaceTokens As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkReplaceTokens control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkReplaceTokens As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowWorkflow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowWorkflow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''cmdWorkflow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdWorkflow As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''plWorkflow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plWorkflow As Global.System.Web.UI.UserControl

        '''<summary>
        '''cboWorkflow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboWorkflow As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rowApplyTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowApplyTo As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plApplyTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plApplyTo As Global.System.Web.UI.UserControl

        '''<summary>
        '''rblApplyTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblApplyTo As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''chkReplace control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkReplace As Global.System.Web.UI.WebControls.CheckBox
    End Class
End Namespace
