'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Messaging.Views

    Partial Public Class EditMessage

        '''<summary>
        '''toFieldLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents toFieldLabel As Global.DotNetNuke.Web.UI.WebControls.DnnFieldLabel

        '''<summary>
        '''toLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents toLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''toTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents toTextBox As Global.DotNetNuke.Web.UI.WebControls.DnnTextBox

        '''<summary>
        '''validateUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents validateUser As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''toValidator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents toValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''subjectFieldLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subjectFieldLabel As Global.DotNetNuke.Web.UI.WebControls.DnnFieldLabel

        '''<summary>
        '''subjectTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subjectTextBox As Global.DotNetNuke.Web.UI.WebControls.DnnTextBox

        '''<summary>
        '''subjectValidator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subjectValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''messageFieldLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents messageFieldLabel As Global.DotNetNuke.Web.UI.WebControls.DnnFieldLabel

        '''<summary>
        '''messageEditor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents messageEditor As Global.DotNetNuke.UI.UserControls.TextEditor

        '''<summary>
        '''saveDraft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents saveDraft As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''sendMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sendMessage As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''deleteHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents deleteHolder As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''deleteMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents deleteMessage As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cancelEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cancelEdit As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
