'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Messaging.Views

    Partial Public Class MessageList

        '''<summary>
        '''titleLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents titleLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''messagesGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents messagesGrid As Global.DotNetNuke.Web.UI.WebControls.DnnGrid

        '''<summary>
        '''addMessageButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addMessageButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''markAsRead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents markAsRead As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''markAsUnread control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents markAsUnread As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''delete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents delete As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
