'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Messaging.Views

    Partial Public Class ViewMessage

        '''<summary>
        '''fromFieldLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fromFieldLabel As Global.DotNetNuke.Web.UI.WebControls.DnnFieldLabel

        '''<summary>
        '''fromLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fromLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''subjectFieldLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subjectFieldLabel As Global.DotNetNuke.Web.UI.WebControls.DnnFieldLabel

        '''<summary>
        '''subjectLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subjectLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''messageLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents messageLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''replyMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents replyMessage As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''deleteMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents deleteMessage As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cancelView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cancelView As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
