'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Taxonomy.Views

    Partial Public Class CreateVocabulary

        '''<summary>
        '''editVocabularyControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents editVocabularyControl As Global.DotNetNuke.Modules.Taxonomy.Views.Controls.EditVocabularyControl

        '''<summary>
        '''saveVocabulary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents saveVocabulary As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''cancelCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cancelCreate As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
