'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Taxonomy.Views

    Partial Public Class EditVocabulary

        '''<summary>
        '''titleLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents titleLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''termsLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents termsLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''termsList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents termsList As Global.DotNetNuke.Modules.Taxonomy.WebControls.TermsList

        '''<summary>
        '''addTermButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addTermButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''termEditor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents termEditor As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''termLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents termLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''editTermControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents editTermControl As Global.DotNetNuke.Modules.Taxonomy.Views.Controls.EditTermControl

        '''<summary>
        '''saveTermButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents saveTermButton As Global.DotNetNuke.Web.UI.WebControls.DnnButton

        '''<summary>
        '''deleteTermPlaceHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents deleteTermPlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''deleteTermButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents deleteTermButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cancelTermButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cancelTermButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''editVocabularyControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents editVocabularyControl As Global.DotNetNuke.Modules.Taxonomy.Views.Controls.EditVocabularyControl

        '''<summary>
        '''saveVocabulary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents saveVocabulary As Global.DotNetNuke.Web.UI.WebControls.DnnButton

        '''<summary>
        '''deleteVocabulary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents deleteVocabulary As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cancelEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cancelEdit As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
