'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Taxonomy.Views

    Partial Public Class VocabularyList

        '''<summary>
        '''titleLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents titleLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''vocabulariesGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vocabulariesGrid As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''addVocabularyButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addVocabularyButton As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
