'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Taxonomy.Views.Controls

    Partial Public Class EditVocabularyControl

        '''<summary>
        '''nameFieldLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents nameFieldLabel As Global.DotNetNuke.Web.UI.WebControls.DnnFieldLabel

        '''<summary>
        '''nameLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents nameLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''nameTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents nameTextBox As Global.DotNetNuke.Web.UI.WebControls.DnnTextBox

        '''<summary>
        '''nameValidator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents nameValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''descriptionFieldLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents descriptionFieldLabel As Global.DotNetNuke.Web.UI.WebControls.DnnFieldLabel

        '''<summary>
        '''descriptionTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents descriptionTextBox As Global.DotNetNuke.Web.UI.WebControls.DnnTextBox

        '''<summary>
        '''typeFieldLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents typeFieldLabel As Global.DotNetNuke.Web.UI.WebControls.DnnFieldLabel

        '''<summary>
        '''typeList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents typeList As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''typeLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents typeLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''scopeRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents scopeRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''scopeFieldLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents scopeFieldLabel As Global.DotNetNuke.Web.UI.WebControls.DnnFieldLabel

        '''<summary>
        '''scopeList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents scopeList As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''scopeLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents scopeLabel As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
