'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Taxonomy.Views.Controls

    Partial Public Class EditTermControl

        '''<summary>
        '''nameFieldLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents nameFieldLabel As Global.DotNetNuke.Web.UI.WebControls.DnnFieldLabel

        '''<summary>
        '''nameTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents nameTextBox As Global.DotNetNuke.Web.UI.WebControls.DnnTextBox

        '''<summary>
        '''nameValidator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents nameValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''descriptionFieldLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents descriptionFieldLabel As Global.DotNetNuke.Web.UI.WebControls.DnnFieldLabel

        '''<summary>
        '''descriptionTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents descriptionTextBox As Global.DotNetNuke.Web.UI.WebControls.DnnTextBox

        '''<summary>
        '''parentTermRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents parentTermRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''parentTermLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents parentTermLabel As Global.DotNetNuke.Web.UI.WebControls.DnnFieldLabel

        '''<summary>
        '''parentTermCombo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents parentTermCombo As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox
    End Class
End Namespace
